package lang.parser;

import lang.ast.cmd.*;
import lang.ast.*;
import lang.ast.expr.*;
import lang.ast.types.*;
import beaver.*;
import java.util.ArrayList;

/**
 * This class is a LALR parser generated by
 * <a href="http://beaver.sourceforge.net">Beaver</a> v0.9.6.1
 * from the grammar specification "Lang.grammar".
 */
public class LangParser extends Parser {

	static final ParsingTables PARSING_TABLES = new ParsingTables(
		"U9pDb3bG544KXl#PNHQHlK0EGGO41UGG3y0RnHDFF2WpCpCpZCmmqiJCigoo32qJImsqJAn" +
		"2iTHCaG2vFC434U#Rg$rxwktGknJ4zDJN$tklNy$qz0LOG1Gha8#5A4GH5iLxwfiQHnBgr2" +
		"ZM80DPc8zSr26PtkAuNllGYFquW0eraj1IWtAae6fAFDR3FwLbDda1xwyFOZVoi8VFDXHZd" +
		"XUlnY76OzuS#EZPgbEDSTvMU$7rI3EowZ7Ny5Anol322DAhPQm68PHmvhup5g5NYmPKkNcQ" +
		"T6n79hAHWrrO00S575Kfbc0fob29PLYEbLYBTTZ0zs$49cocRiKMrZl93knLFQfRTQcdt08" +
		"sH#tdU0DSsNWl0Z2IpZg3$vR2SQVI2zABpylaYB8v$YZ77D$Yy9yAE9$1QNeKJkancppR##" +
		"iYFc7EiPvbc#iVYmVv1s7FI#CAXBdZAznvCxFoZAmWTzYa5#8SJNfw1uQvxWwVY3jp4JVcC" +
		"AOzdQTn#1R7VQAYDYCv$6ePYKh4uPT2dkPpfuHSAuqviGTeEWctwDNMQtr5$3CaHCwHN793" +
		"uW7Igct5GcaZvqazEIqv3QADeeT9Epb2EiXH4YJ7T7iYBFsabFIGH#GToPAsGIElbpIJc#G" +
		"4EIlnsw8NH3#I5dAP34Zi2pb5hfBtf8yCITiJye5Kas69bOYEY8wICJ9E9XB6toAQRyIQHV" +
		"KSNnJxaj5#pR1R3VkkQ9leFT7xeWz47vfZI1ZFTSE#CqFUOz7swNAalSDKiJiJj2kXpotIA" +
		"$RncTvlz6c253K1hwY$RltRhL#wzLV2DLP3XEkck9wAUqODghVgZHfG$PBtogrVarxLf$vH" +
		"dxcH5#gvudvGdxrlV89HrB1d$I6$o0ylyjCz1UKy#nQnQMdFuYrWySo2MBmb0YIPfy$7VQs" +
		"nUAFOFDaQYsVSJxJQFEb9HD#TFWFRiAq4TAvVR1zl2Olut9kWZ5fCDQdy3wyUxWu=");

	private final Action[] actions;

	public LangParser() {
		super(PARSING_TABLES);
		actions = new Action[] {
			new Action() {	// [0] lst$functionDec = functionDec
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [1] lst$functionDec = lst$functionDec functionDec
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			Action.NONE,  	// [2] opt$lst$functionDec = 
			Action.RETURN,	// [3] opt$lst$functionDec = lst$functionDec
			new Action() {	// [4] program = opt$lst$functionDec.decs
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_decs = _symbols[offset + 1];
					final ArrayList _list_decs = (ArrayList) _symbol_decs.value;
					final Func[] decs = _list_decs == null ? new Func[0] : (Func[]) _list_decs.toArray(new Func[_list_decs.size()]);
					 return new Program(decs);
				}
			},
			Action.NONE,  	// [5] opt$argList = 
			Action.RETURN,	// [6] opt$argList = argList
			new Action() {	// [7] functionDec = ID.n LPAREN RPAREN COLON opt$argList.l block.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final String n = (String) _symbol_n.value;
					final Symbol _symbol_l = _symbols[offset + 5];
					final ArrayList _list_l = (ArrayList) _symbol_l.value;
					final Expr[] l = _list_l == null ? new Expr[0] : (Expr[]) _list_l.toArray(new Expr[_list_l.size()]);
					final Symbol _symbol_b = _symbols[offset + 6];
					final Cmd b = (Cmd) _symbol_b.value;
					return new Func(l, n, new Pair[0], b);
				}
			},
			new Action() {	// [8] functionDec = ID.n LPAREN varDecList.p RPAREN COLON opt$argList.l block.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final String n = (String) _symbol_n.value;
					final Symbol _symbol_p = _symbols[offset + 3];
					final ArrayList _list_p = (ArrayList) _symbol_p.value;
					final Pair[] p = _list_p == null ? new Pair[0] : (Pair[]) _list_p.toArray(new Pair[_list_p.size()]);
					final Symbol _symbol_l = _symbols[offset + 6];
					final ArrayList _list_l = (ArrayList) _symbol_l.value;
					final Expr[] l = _list_l == null ? new Expr[0] : (Expr[]) _list_l.toArray(new Expr[_list_l.size()]);
					final Symbol _symbol_b = _symbols[offset + 7];
					final Cmd b = (Cmd) _symbol_b.value;
					return new Func(l, n, p, b);
				}
			},
			new Action() {	// [9] block = LBRACE commandList.c RBRACE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_c = _symbols[offset + 2];
					final Cmd c = (Cmd) _symbol_c.value;
					 return c;
				}
			},
			new Action() {	// [10] varDecList = varDecList COMMA varDec
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 3].value); return _symbols[offset + 1];
				}
			},
			new Action() {	// [11] varDecList = varDec
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [12] varDec = type.t ID.i
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 1];
					final SType t = (SType) _symbol_t.value;
					final Symbol _symbol_i = _symbols[offset + 2];
					final String i = (String) _symbol_i.value;
					  return new Pair(t,i);
				}
			},
			new Action() {	// [13] commandList = cmd.c commandList.l
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_c = _symbols[offset + 1];
					final Cmd c = (Cmd) _symbol_c.value;
					final Symbol _symbol_l = _symbols[offset + 2];
					final Cmd l = (Cmd) _symbol_l.value;
					 return new Seq(c,l);
				}
			},
			new Action() {	// [14] commandList = cmd.c
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_c = _symbols[offset + 1];
					final Cmd c = (Cmd) _symbol_c.value;
					 return c;
				}
			},
			new Action() {	// [15] cmd = ID.v ATTR expr.e SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					 return new Attr(v,e);
				}
			},
			new Action() {	// [16] cmd = stmt.s
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_s = _symbols[offset + 1];
					final Cmd s = (Cmd) _symbol_s.value;
					 return s;
				}
			},
			new Action() {	// [17] cmd = expr.e SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 1];
					final Expr e = (Expr) _symbol_e.value;
					 return new ExpCmd(e);
				}
			},
			new Action() {	// [18] stmt = WHILE LPAREN expr.e RPAREN block.c
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_c = _symbols[offset + 5];
					final Cmd c = (Cmd) _symbol_c.value;
					 return new While(e,c);
				}
			},
			new Action() {	// [19] stmt = IF LPAREN expr.e RPAREN block.c ELSE block.d
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_c = _symbols[offset + 5];
					final Cmd c = (Cmd) _symbol_c.value;
					final Symbol _symbol_d = _symbols[offset + 7];
					final Cmd d = (Cmd) _symbol_d.value;
					 return new If(e,c,d);
				}
			},
			new Action() {	// [20] expr = expr.a PLUS expr.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final Expr a = (Expr) _symbol_a.value;
					final Symbol _symbol_b = _symbols[offset + 3];
					final Expr b = (Expr) _symbol_b.value;
					 return new Add(a ,b);
				}
			},
			new Action() {	// [21] expr = expr.a MINUS expr.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final Expr a = (Expr) _symbol_a.value;
					final Symbol _symbol_b = _symbols[offset + 3];
					final Expr b = (Expr) _symbol_b.value;
					 return new Sub(a ,b);
				}
			},
			new Action() {	// [22] expr = expr.a EQ expr.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final Expr a = (Expr) _symbol_a.value;
					final Symbol _symbol_b = _symbols[offset + 3];
					final Expr b = (Expr) _symbol_b.value;
					 return new Eq(a ,b);
				}
			},
			new Action() {	// [23] expr = NOT expr.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expr e = (Expr) _symbol_e.value;
					 return new Not(e);
				}
			},
			new Action() {	// [24] expr = expr.a LT expr.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final Expr a = (Expr) _symbol_a.value;
					final Symbol _symbol_b = _symbols[offset + 3];
					final Expr b = (Expr) _symbol_b.value;
					 return new Lt(a ,b);
				}
			},
			new Action() {	// [25] expr = expr.a AND expr.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final Expr a = (Expr) _symbol_a.value;
					final Symbol _symbol_b = _symbols[offset + 3];
					final Expr b = (Expr) _symbol_b.value;
					 return new And(a ,b);
				}
			},
			new Action() {	// [26] expr = NUMBER.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Integer n = (Integer) _symbol_n.value;
					 return new IntLit(n);
				}
			},
			new Action() {	// [27] expr = TRUE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new BoolLit(true);
				}
			},
			new Action() {	// [28] expr = FALSE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new BoolLit(false);
				}
			},
			new Action() {	// [29] expr = STRING.s
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_s = _symbols[offset + 1];
					final String s = (String) _symbol_s.value;
					 return new StrLit(s);
				}
			},
			new Action() {	// [30] expr = ID.v LPAREN opt$argList.c RPAREN RTL retList.l RTR
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_c = _symbols[offset + 3];
					final ArrayList _list_c = (ArrayList) _symbol_c.value;
					final Expr[] c = _list_c == null ? new Expr[0] : (Expr[]) _list_c.toArray(new Expr[_list_c.size()]);
					final Symbol _symbol_l = _symbols[offset + 6];
					final ArrayList _list_l = (ArrayList) _symbol_l.value;
					final String[] l = _list_l == null ? new String[0] : (String[]) _list_l.toArray(new String[_list_l.size()]);
					 return new Call(v, c, l);
				}
			},
			new Action() {	// [31] expr = ID.v LPAREN opt$argList.c RPAREN
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_c = _symbols[offset + 3];
					final ArrayList _list_c = (ArrayList) _symbol_c.value;
					final Expr[] c = _list_c == null ? new Expr[0] : (Expr[]) _list_c.toArray(new Expr[_list_c.size()]);
					 return new Call(v, c, new String[0]);
				}
			},
			new Action() {	// [32] expr = ID.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					 return new Var(v);
				}
			},
			new Action() {	// [33] expr = LPAREN expr.e RPAREN
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expr e = (Expr) _symbol_e.value;
					 return e;
				}
			},
			new Action() {	// [34] argList = expr
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [35] argList = argList COMMA expr
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 3].value); return _symbols[offset + 1];
				}
			},
			new Action() {	// [36] retList = ID.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [37] retList = retList COMMA ID.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 3];
					final String v = (String) _symbol_v.value;
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 3].value); return _symbols[offset + 1];
				}
			},
			new Action() {	// [38] type = BOOL
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyBool();
				}
			},
			new Action() {	// [39] type = INT
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyInt();
				}
			},
			new Action() {	// [40] type = STR
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyString();
				}
			},
			new Action() {	// [41] type = VOID
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyVoid();
				}
			}
		};
	}

	protected Symbol invokeReduceAction(int rule_num, int offset) {
		return actions[rule_num].reduce(_symbols, offset);
	}
}
